


import Head from 'next/head'
import Image from 'next/image'
import markdownText from '../strings/markdown-strings.js'
import MarkdownOptions from '@/components/options.js'
import Markdown from '@/components/markdown.js'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })


export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <h1> Markdown Generator </h1>

        <div>A simple Markdown generator using mock blog data - either copy
          and paste the existing markdown or generate your own using the options below. Use this as a 
          starting point to quickly get the mock markdown data you need (https://www.markdownguide.org/basic-syntax/).  </div> 
        <Markdown /> 
      </main>
    </>
  )
}
