import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [markdownObj, setMarkdownObj] = useState([]);
  // const [htmlString, setHtmlString] = useState({});

  function grabData() {
        var elements = document.getElementById("myForm").elements;
        var obj ={};
          for(var i = 0 ; i < elements.length ; i++){
              var item = elements.item(i);
              obj[item.name] = item.value;
          }
        const propertyValues = Object.values(obj);


        setMarkdownObj(propertyValues);
        document.getElementById("myForm").reset();
        // generateString();
        console.log('markdown obj', markdownObj)
    }

    // function generateString() {
    //   const propertyValues = Object.values(markdownObj);
    //   setHtmlString(propertyValues)
    //   console.log('generated string', generateString)
    // }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <form id="myForm" action="/my-handling-form-page" method="post">

                <label htmlFor="name">Name:</label>
                <input type="text" id="name" name="user_name" />

                <label htmlFor="mail">Email:</label>
                <input type="email" id="mail" name="user_email" />

                <label htmlFor="msg">Message:</label>
                <textarea id="msg" name="user_message"></textarea>

          </form>

        <button onClick={() => grabData()}> Hello World </button>
        <div> {markdownObj} </div> 
      
      </main>
    </>
  )
}
